"""
Build a Protocol → Handler topology doc from the runtime scan
(buildProtoHandlerMap RPC, output saved to %TEMP%/proto_handlers.json).

Even though both message classes (Protocol.Game) and handler classes (Core)
are obfuscated, the structural mapping lets us:
  - Identify the central message dispatcher classes (those handling many
    distinct messages → likely service hubs)
  - Cluster obfuscated handler classes by domain (e.g. all inventory
    messages route to the same handler → that handler is "inventory")
  - Bootstrap further deobfuscation: when one message name is recovered
    (via FileDescriptor or a hook), the cluster around it cascades.

Output: dofus-app/docs/protocol-handlers.md
"""
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

TEMP = Path(r"C:\Users\Romann\AppData\Local\Temp")
SRC = TEMP / "proto_handlers.json"
DOC_OUT = Path(__file__).resolve().parents[1] / "docs" / "protocol-handlers.md"
DEOBF = Path(__file__).resolve().parents[1] / "docs" / "deobfuscation-map.json"

if not SRC.exists():
    sys.exit(f"missing {SRC} — run buildProtoHandlerMap RPC first")

raw = json.load(SRC.open(encoding="utf-8"))["result"]
messages = raw["messages"]
handlers = raw["handlers"]

print(f"Messages indexed: {len(messages)}")
print(f"Handler hits: {len(handlers)}")

# Stats
msg_handlers = defaultdict(set)        # message → set of handler classes
class_messages = defaultdict(set)      # handler class → set of messages
class_methods = defaultdict(list)      # handler class → list of (msg, method, sig)
for h in handlers:
    msg_handlers[h["msg"]].add(h["handlerClass"])
    class_messages[h["handlerClass"]].add(h["msg"])
    class_methods[h["handlerClass"]].append((h["msg"], h["methodName"], h["signature"]))

distinct_msg = len(msg_handlers)
distinct_class = len(class_messages)
print(f"Distinct messages with handlers: {distinct_msg}")
print(f"Distinct handler classes: {distinct_class}")

# Existing deobf map (for labels)
deobf_labels = {}
if DEOBF.exists():
    deobf = json.load(DEOBF.open(encoding="utf-8"))
    for idx in deobf.get("identifications", []):
        # idx["obf"] could be "Core.X.Y.Name" or just "Name"; pull simple
        simple = idx["obf"].split(".")[-1]
        if idx.get("label") and idx["label"] != "?":
            deobf_labels[simple] = idx["label"]

# ---------- Build doc ----------
md = ["# Dofus 3.0 — Protocol handlers topology\n\n"]
md.append("Generated by `build-protocol-handlers.py` from a runtime IL2CPP scan.\n\n")
md.append("**What this is**: a complete mapping `obfuscated_protocol_message → handler_class` extracted by scanning every method in `Core` whose parameter type is a Protobuf message class from `Ankama.Dofus.Protocol.Game`.\n\n")
md.append("**What's still missing**: the original `.proto` names for each message (blocked at runtime — see `dofus-deobfuscation-roadmap.md` #1). The structural map below lets us cluster handlers by domain, and any future name recovery cascades through the graph.\n\n")
md.append("## Stats\n\n")
md.append(f"- **{len(messages)}** Protobuf message classes detected (have static `MessageParser<Self>` field)\n")
md.append(f"- **{distinct_msg}** distinct messages have at least one handler in `Core` ({100*distinct_msg/len(messages):.0f}%)\n")
md.append(f"- **{distinct_class}** distinct handler classes in `Core` (= dispatcher hubs)\n")
md.append(f"- **{sum(len(v) for v in class_methods.values())}** total handler methods\n\n")

# 1:1 messages
one_to_one = [(m, list(h)[0]) for m, h in msg_handlers.items() if len(h) == 1]
md.append(f"- **{len(one_to_one)}** messages have exactly 1 handler (clean 1:1 dispatch)\n\n")

# ---------- Top dispatchers ----------
md.append("## Top dispatcher classes (by # of distinct messages handled)\n\n")
md.append("These are likely the service hubs that listen to all messages of one domain (Inventory, Combat, World, Chat...). The label is from the existing deobfuscation map when known.\n\n")
md.append("| Rank | Obf | Label | # messages | Sample messages |\n")
md.append("|---|---|---|---|---|\n")
top = sorted(class_messages.items(), key=lambda x: -len(x[1]))[:30]
for i, (cls, msgs) in enumerate(top, 1):
    label = deobf_labels.get(cls, "?")
    sample = ", ".join(f"`{m}`" for m in sorted(msgs)[:5])
    md.append(f"| {i} | `{cls}` | {label} | {len(msgs)} | {sample} |\n")

# ---------- Top messages ----------
md.append("\n## Top messages (by # of handlers — likely fundamental events)\n\n")
md.append("Messages handled by many classes are typically domain-spanning events (e.g. character info update, login state change, frame events).\n\n")
md.append("| Obf | # handlers | Sample handlers |\n|---|---|---|\n")
for msg, hs in sorted(msg_handlers.items(), key=lambda x: -len(x[1]))[:25]:
    sample = ", ".join(f"`{h}`" for h in sorted(hs)[:5])
    md.append(f"| `{msg}` | {len(hs)} | {sample} |\n")

# ---------- 1:1 handlers ----------
md.append("\n## Single-handler messages (1:1 mapping — easiest to label)\n\n")
md.append("These messages have exactly one handler class — when the message name is recovered, both ends get a stable name. Dump truncated to 60.\n\n")
md.append("| Message | Sole handler | Method |\n|---|---|---|\n")
one_to_one_full = []
for m, hs in msg_handlers.items():
    if len(hs) == 1:
        cls = list(hs)[0]
        # find the method name
        method_name = ""
        for msg, mn, sig in class_methods[cls]:
            if msg == m:
                method_name = mn; break
        one_to_one_full.append((m, cls, method_name))
one_to_one_full.sort()
for m, cls, mn in one_to_one_full[:60]:
    label = f" *({deobf_labels[cls]})*" if cls in deobf_labels else ""
    md.append(f"| `{m}` | `{cls}`{label} | `{mn}` |\n")

# ---------- Handler signature analysis ----------
md.append("\n## Handler signature patterns\n\n")
sig_patterns = Counter()
for h in handlers:
    sig = h["signature"]
    # Strip parameter names and method name
    rt = sig.split(" ", 1)[0]
    paren = sig.split("(", 1)[1].rstrip(")")
    param_types = ", ".join(p.split()[0] for p in paren.split(", ") if p)
    pattern = f"{rt} HANDLER({param_types})"
    sig_patterns[pattern] += 1
md.append("| Signature pattern | Count |\n|---|---|\n")
for sig, n in sig_patterns.most_common(15):
    md.append(f"| `{sig}` | {n} |\n")

md.append("\n## Bonus leak: messages whose handler is a CLEAR-named class\n\n")
md.append("Some obfuscated messages have at least one handler whose class name was preserved (`[DoNotRename]` or in a clear namespace). The handler's name strongly hints at the message's purpose. **17 messages identified this way**, listed below.\n\n")
md.append("| Obf message | Clear handler(s) | Likely role |\n|---|---|---|\n")
import re as _re
def _is_obf(n): return bool(_re.match(r'^[a-z]{1,3}(`\d+)?$', n))
msg_clear_handlers = defaultdict(set)
for h in handlers:
    if not _is_obf(h["handlerClass"]):
        msg_clear_handlers[h["msg"]].add(h["handlerClass"])
for m, hs in sorted(msg_clear_handlers.items(), key=lambda x: -len(x[1])):
    uniq = sorted(hs)
    role_guess = uniq[0]
    if len(uniq) > 1:
        # find a common substring
        common = uniq[0]
        for u in uniq[1:]:
            while common and not u.startswith(common):
                common = common[:-1]
        if len(common) > 3:
            role_guess = common + "*"
    md.append(f"| `{m}` | {', '.join(f'`{u}`' for u in uniq)} | **{role_guess}** |\n")

md.append("\n## Domain clusters from message labels\n\n")
md.append("Using the 17 labeled messages, we can identify domain hubs:\n\n")
# For each labeled message, find which obf dispatchers handle it → those dispatchers are in that domain
labeled_msgs = set(msg_clear_handlers.keys())
domain_dispatchers = defaultdict(set)  # handler class → set of (msg, label)
for h in handlers:
    if h["msg"] in labeled_msgs and _is_obf(h["handlerClass"]):
        for clear in msg_clear_handlers[h["msg"]]:
            domain_dispatchers[h["handlerClass"]].add((h["msg"], clear))
md.append("| Obf dispatcher | Labeled messages it handles | Inferred role |\n|---|---|---|\n")
for cls, evidence in sorted(domain_dispatchers.items(), key=lambda x: -len(x[1]))[:30]:
    msgs_str = ", ".join(f"`{m}`→{c}" for m, c in sorted(evidence)[:4])
    # Pick the dominant clear-class as the label
    counter = Counter(c for _, c in evidence)
    top_clear = counter.most_common(1)[0][0]
    md.append(f"| `{cls}` | {msgs_str} | **service related to `{top_clear}`** |\n")

md.append("\n## Re-using this map\n\n")
md.append("Once we recover the original .proto name for any single message (e.g. via `FileDescriptor.FromGeneratedCode` invocation, or by hooking `MessageParser<T>.ParseFrom` at runtime when a real packet arrives), the cluster around it becomes labeled too. The JSON output `protocol-handlers.json` is the machine-readable source of truth, and `protocol-message-labels.json` lists the 17 messages already identified by clear-handler leak.\n")

# ---------- Save ----------
DOC_OUT.parent.mkdir(parents=True, exist_ok=True)
DOC_OUT.write_text("".join(md), encoding="utf-8")
print(f"\nWrote {DOC_OUT}")

# Save JSON
JSON_OUT = DOC_OUT.with_suffix(".json")
out_data = {
    "stats": {
        "totalMessages": len(messages),
        "messagesWithHandlers": distinct_msg,
        "distinctHandlerClasses": distinct_class,
        "totalHandlerHits": sum(len(v) for v in class_methods.values()),
        "oneToOneMessages": len(one_to_one_full),
    },
    "messageHandlers": {m: sorted(list(h)) for m, h in msg_handlers.items()},
    "classHandledMessages": {c: sorted(list(m)) for c, m in class_messages.items()},
    "topDispatchers": [
        {"obf": cls, "label": deobf_labels.get(cls, "?"), "messageCount": len(msgs), "messages": sorted(list(msgs))}
        for cls, msgs in top
    ],
    "oneToOneFull": [
        {"message": m, "handler": cls, "handlerLabel": deobf_labels.get(cls, "?"), "method": mn}
        for m, cls, mn in one_to_one_full
    ],
}
JSON_OUT.write_text(json.dumps(out_data, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"Wrote {JSON_OUT}")
