import * as fs from "node:fs";
import * as path from "node:path";

const DTS_CONTENT = `// AUTO-GENERATED by frida-il2cpp-toolkit. Do not edit by hand.

declare module "@toolkit/scripts" {
    export type ParamSpec =
        | { type: "string";  label?: string; required?: boolean; default?: string;  placeholder?: string }
        | { type: "number";  label?: string; required?: boolean; default?: number;  min?: number; max?: number }
        | { type: "boolean"; label?: string; default?: boolean }
        | { type: "enum";    label?: string; values: readonly string[]; default?: string };

    export type ParamSchema = Record<string, ParamSpec>;

    export interface ScriptDefinition<P extends Record<string, unknown> = Record<string, unknown>> {
        name: string;
        description?: string;
        params: { [K in keyof P]: ParamSpec };
        timeoutMs?: number;
        run: (args: P, toolkit: Toolkit) => Promise<unknown>;
    }

    export type InstanceHandle = { className: string; handle: string; key: string };
    export type HookHandle = { id: string };

    export interface CaptureOpts { asKey?: string; index?: number }
    export interface HookInstallOpts { mode?: "log" | "modify-return"; returnValue?: unknown }
    export interface HookCallEvent { args: unknown[]; ts: string }
    export interface NetworkPacket {
        id: string; direction: "in" | "out"; messageType: string; payload: unknown; ts: number;
    }

    export interface Toolkit {
        instances: {
            find(label: string): Promise<InstanceHandle>;
            findAll(label: string): Promise<InstanceHandle[]>;
            capture(label: string, opts?: CaptureOpts): Promise<InstanceHandle>;
            read(handle: InstanceHandle, field: string): Promise<unknown>;
            write(handle: InstanceHandle, field: string, value: unknown): Promise<void>;
            call(handle: InstanceHandle, method: string, args?: unknown[]): Promise<unknown>;
            list(): Promise<InstanceHandle[]>;
        };
        hooks: {
            install(target: string, opts: HookInstallOpts): Promise<HookHandle>;
            remove(handle: HookHandle): Promise<void>;
            onceCall(target: string, opts?: { timeoutMs?: number }): Promise<HookCallEvent>;
        };
        network: {
            send(messageType: string, payload: Record<string, unknown>): Promise<void>;
            onceReceive(messageType: string, opts?: { timeoutMs?: number }): Promise<NetworkPacket>;
            recent(messageType?: string, limit?: number): Promise<NetworkPacket[]>;
        };
        log:   (...args: unknown[]) => void;
        warn:  (...args: unknown[]) => void;
        error: (...args: unknown[]) => void;
        sleep: (ms: number) => Promise<void>;
    }

    export function defineScript<P extends Record<string, unknown>>(def: ScriptDefinition<P>): ScriptDefinition<P>;
}
`;

const TSCONFIG = {
    compilerOptions: {
        target: "ES2022",
        module: "esnext",
        moduleResolution: "node",
        strict: true,
        noEmit: true,
        skipLibCheck: true,
        paths: { "@toolkit/scripts": ["./_types/toolkit.d.ts"] },
    },
    include: ["**/*.ts"],
    exclude: ["_types/**", "node_modules/**"],
};

export function emitScriptsTypes(scriptsDir: string): void {
    fs.mkdirSync(path.join(scriptsDir, "_types"), { recursive: true });
    fs.writeFileSync(path.join(scriptsDir, "_types", "toolkit.d.ts"), DTS_CONTENT, "utf8");
    fs.writeFileSync(path.join(scriptsDir, "tsconfig.json"), JSON.stringify(TSCONFIG, null, 2), "utf8");
}
